version: '3'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
      MYSQL_USER: john
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: john
      PMA_PASSWORD: secret
    ports:
      - "8080:80"

  app:
    depends_on:
      - db
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=john
      - DATABASE_PASSWORD=secret
      - DATABASE_NAME=mydb

volumes:
  db_data: